import Layout from "@/components/Layout";
import Head from "next/head";
import profilePic from "../../public/images/profile/programmer.jpg";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { ContactIcon, LinkArrow } from "@/components/icons";

export default function Home() {
    return (
        <>
            <Head>
                <title>JPM | Home Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
                <Layout className="pt-0 md:pt-16 sm:pt-8">
                    <div className="flex items-center justify-between w-full lg:flex-col">
                        <div className="w-1/2 mr-8 md:w-full md:mr-0">
                            <Image
                                src={profilePic}
                                priority
                                alt="James"
                                className="w-full h-auto rounded-full lg:hidden md:inline-block md:w-full "
                                sizes="(max-width: 768px) 100vw,
                                        (max-width: 1200px) 50vw,
                                        33vw"
                            />
                        </div>
                        <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
                            <AnimatedText
                                text="Transforming Ideas into Functional Websites."
                                className=" text-left"
                            />

                            <p className="my-4 text-base font-medium cursor-default md:text-sm sm:text-xs">
                                Full Stack Web Developer with a Passion for
                                Creating Engaging User Experiences
                            </p>
                            <div className="flex items-center self-start t-2 lg:self-center">
                                <Link
                                    href="/resume.pdf"
                                    target="_blank"
                                    download={true}
                                    className="flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold transition-all hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                                >
                                    Resume <LinkArrow className={"w-6 ml-1 "} />
                                </Link>
                                <Link
                                    href="mailto:royamsemaj@gmail.com"
                                    className="flex items-center gap-1 ml-4 text-lg font-medium capitalize text-dark underline underline-offset-2
                                    hover:scale-[1.03] transition-all dark:text-light md:text-base"
                                >
                                    Contact <ContactIcon />
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
            </main>
        </>
    );
}
